apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: data-pipeline
  labels:
    app: hive-metastore
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
  selector:
    app: hive-metastore
