apiVersion: v1
kind: Service
metadata:
  name: hms-postgres
  namespace: data-pipeline
  labels:
    app: hms-postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: hms-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: hms-postgres-headless
  namespace: data-pipeline
  labels:
    app: hms-postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: hms-postgres
